In [1]:
from time import perf_counter
start = perf_counter()
from shapely.geometry import Point
print(f'imported Point in {perf_counter() - start:.3f} sec')
start = perf_counter()
import geopandas as gpd
print(f'imported gpd in {perf_counter() - start:.3f} sec')
start = perf_counter()
import pandas as pd
print(f'imported pd in {perf_counter() - start:.3f} sec')
start = perf_counter()
import numpy as np
print(f'imported np in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.data_gen.region_generator import RegionGenerator
print(f'imported RegionGen in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.data.measurment import Measurement
print(f'imported Measurement in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.grouping.brute_force import Brute_Force
print(f'imported BruteF in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.controller.benchmark_runner import BenchmarkRunner
print(f'imported Benchmark in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.animation.animation import Animation
print(f'imported Animation in {perf_counter() - start:.3f} sec')
start = perf_counter()
import plotly.graph_objects as go
print(f'imported Go in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.animation.trajectory import Trajectory
print(f'imported traj in {perf_counter() - start:.3f} sec')
start = perf_counter()
import plotly.express as px
print(f'imported px in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.utilities.seed_container import Seed_Container
print(f'imported SeedContainer in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.data.grouped_region import GroupedRegion
print(f'imported Grouped_Region in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.grouping.genetic import Genetic
print(f'imported Genetic in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.grouping.k_means import K_Means
print(f'imported K-Means in {perf_counter() - start:.3f} sec')

imported Point in 0.256 sec
imported gpd in 0.643 sec
imported pd in 0.000 sec
imported np in 0.000 sec
imported RegionGen in 0.256 sec
imported Measurement in 0.015 sec
imported BruteF in 0.708 sec
imported Benchmark in 0.003 sec
imported Animation in 0.001 sec
imported Go in 0.000 sec
imported traj in 0.000 sec
imported px in 0.215 sec
imported SeedContainer in 0.000 sec
imported Grouped_Region in 0.000 sec
imported Genetic in 0.001 sec
imported K-Means in 2.187 sec

In [7]:
sc = Seed_Container(seed=None)
region = RegionGenerator(seed_container=sc).random(50, 1, 10)
algo = K_Means(sc, 1, 5, 10)
result = algo.group(region=region, animate=True)
animation = Animation().play(algo.get_trajectory())

warum nur alle 3 schritte änderung? warum bei distance weight 1 nicht gruppen bildung,

In [3]:
print(f'before: {result.get_autarky_without_groups():.3f}, after: {result.region_autarky():.3f}')

result.houses

before: 0.694, after: 0.878

       coordinate load  gen                     id  label
0   POINT (17 46)  [9]  [9]  X17.000000|Y46.000000      3
1   POINT (26 85)  [3]  [3]  X26.000000|Y85.000000      4
2   POINT (71 87)  [8]  [5]  X71.000000|Y87.000000      0
3   POINT (29 20)  [9]  [4]  X29.000000|Y20.000000      3
4   POINT (62 32)  [9]  [3]  X62.000000|Y32.000000      2
5   POINT (69 13)  [6]  [3]  X69.000000|Y13.000000      2
6   POINT (54 22)  [3]  [3]  X54.000000|Y22.000000      2
7   POINT (26 42)  [2]  [2]  X26.000000|Y42.000000      3
8    POINT (2 85)  [1]  [2]   X2.000000|Y85.000000      4
9   POINT (45 83)  [5]  [3]  X45.000000|Y83.000000      0
10  POINT (22 87)  [5]  [8]  X22.000000|Y87.000000      4
11  POINT (17 76)  [3]  [3]  X17.000000|Y76.000000      4
12  POINT (81 57)  [3]  [6]  X81.000000|Y57.000000      0
13  POINT (92 33)  [4]  [7]  X92.000000|Y33.000000      2
14  POINT (20 56)  [9]  [5]  X20.000000|Y56.000000      4
15  POINT (65 88)  [5]  [3]  X65.000000|Y88.000000      0
16  POINT (96 48)  [6]  [8]  X96.000000|Y48.000000      2
17  POINT (52 51)  [2]  [4]  X52.000000|Y51.000000      1
18  POINT (98 42)  [9]  [3]  X98.000000|Y42.000000      2
19  POINT (43 51)  [1]  [2]  X43.000000|Y51.000000      1
20  POINT (24 47)  [8]  [1]  X24.000000|Y47.000000      3
21  POINT (32 57)  [2]  [6]  X32.000000|Y57.000000      1
22  POINT (89 91)  [2]  [9]  X89.000000|Y91.000000      0
23  POINT (87 33)  [6]  [6]  X87.000000|Y33.000000      2
24  POINT (19 75)  [5]  [6]  X19.000000|Y75.000000      4
25  POINT (24 68)  [2]  [6]  X24.000000|Y68.000000      4
26  POINT (65 23)  [3]  [3]  X65.000000|Y23.000000      2
27  POINT (25 27)  [5]  [9]  X25.000000|Y27.000000      3
28  POINT (35 86)  [6]  [4]  X35.000000|Y86.000000      4
29  POINT (53 67)  [1]  [8]  X53.000000|Y67.000000      0
30  POINT (86 18)  [8]  [3]  X86.000000|Y18.000000      2
31  POINT (59 68)  [8]  [7]  X59.000000|Y68.000000      0
32  POINT (62 24)  [4]  [9]  X62.000000|Y24.000000      2
33  POINT (35 49)  [4]  [7]  X35.000000|Y49.000000      1
34  POINT (20 30)  [2]  [6]  X20.000000|Y30.000000      3
35  POINT (42 64)  [6]  [4]  X42.000000|Y64.000000      1
36  POINT (66 55)  [4]  [9]  X66.000000|Y55.000000      1
37  POINT (75 70)  [2]  [2]  X75.000000|Y70.000000      0
38  POINT (14 20)  [9]  [2]  X14.000000|Y20.000000      3
39  POINT (14 26)  [1]  [6]  X14.000000|Y26.000000      3
40  POINT (13 61)  [5]  [3]  X13.000000|Y61.000000      4
41  POINT (45 29)  [4]  [7]  X45.000000|Y29.000000      1
42  POINT (50 22)  [9]  [4]  X50.000000|Y22.000000      2
43  POINT (53 45)  [9]  [9]  X53.000000|Y45.000000      1
44  POINT (16 60)  [3]  [1]  X16.000000|Y60.000000      4
45  POINT (67 38)  [5]  [3]  X67.000000|Y38.000000      2
46  POINT (25 81)  [2]  [9]  X25.000000|Y81.000000      4
47  POINT (48 18)  [9]  [2]  X48.000000|Y18.000000      2
48  POINT (43 86)  [2]  [9]  X43.000000|Y86.000000      0
49  POINT (82 78)  [7]  [5]  X82.000000|Y78.000000      0

In [4]:
print(f'seed: {sc.seed()}')

seed: 3411045360

In [5]:
result = BenchmarkRunner(algo=Brute_Force(.5)).run(
    max_houses=6, 
    max_time_steps=24, 
    house_interval=2, 
    time_step_interval=24,
    file_location="C:/Users/steve/OneDrive/Dokumente/Universität/BA/Messung"
)
result

finished house 2/6 in 0.019 seconds
finished house 4/6 in 0.140 seconds
finished house 6/6 in 2.147 seconds

time_step_count        24
house_count
2                0.019406
4                0.140327
6                2.146633

In [6]:
x = np.array([1,-2])/np.array([1,2]).max()
x

array([ 0.5, -1. ])