In [1]:
from time import perf_counter
start = perf_counter()
from shapely.geometry import Point
print(f'imported Point in {perf_counter() - start:.3f} sec')
start = perf_counter()
import geopandas as gpd
print(f'imported gpd in {perf_counter() - start:.3f} sec')
start = perf_counter()
import pandas as pd
print(f'imported pd in {perf_counter() - start:.3f} sec')
start = perf_counter()
import numpy as np
print(f'imported np in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.data_gen.region_generator import RegionGenerator
print(f'imported RegionGen in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.data.measurment import Measurement
print(f'imported Measurement in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.grouping.brute_force import Brute_Force
print(f'imported BruteF in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.controller.benchmark_runner import BenchmarkRunner
print(f'imported Benchmark in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.grouping.k_means import K_Means
print(f'imported K-Means in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.animation.animation import Animation
print(f'imported Animation in {perf_counter() - start:.3f} sec')
start = perf_counter()
import plotly.graph_objects as go
print(f'imported Go in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.animation.trajectory import Trajectory
print(f'imported traj in {perf_counter() - start:.3f} sec')
import plotly.express as px

imported Point in 0.228 sec
imported gpd in 0.660 sec
imported pd in 0.000 sec
imported np in 0.000 sec
imported RegionGen in 0.290 sec
imported Measurement in 0.004 sec
imported BruteF in 0.663 sec
imported Benchmark in 0.002 sec
imported K-Means in 2.026 sec
imported Animation in 0.001 sec
imported Go in 0.000 sec
imported traj in 0.000 sec

In [ ]:
region = RegionGenerator(3).random(6, 1, 10)
algo = Brute_Force(distance_weight=0)
result = algo.group(region=region, animate=False)
# animation = Animation().play(algo.get_trajectory())

In [7]:
print(f'before: {result.get_autarky_without_groups():.3f}, after: {result.region_autarky():.3f}')

result.houses

before: 0.636, after: 0.788

            coordinate load  gen                   id  label
0  POINT (5.941 0.998)  [7]  [2]  X5.941120|Y0.998053      0
1   POINT (4.995 0.32)  [6]  [8]  X4.994827|Y0.319668      1
2  POINT (7.032 8.674)  [8]  [5]  X7.031682|Y8.673677      2
3  POINT (9.368 6.794)  [9]  [5]  X9.368175|Y6.794439      1
4  POINT (0.482 0.467)  [3]  [6]  X0.481660|Y0.467176      0

In [4]:
result = BenchmarkRunner(algo=Brute_Force(.5)).run(
    max_houses=6, 
    max_time_steps=24, 
    house_interval=2, 
    time_step_interval=24,
    file_location="C:/Users/steve/OneDrive/Dokumente/Universität/BA/Messung"
)
result

finished house 2/6 in 0.019 seconds
finished house 4/6 in 0.230 seconds
finished house 6/6 in 1.828 seconds

time_step_count        24
house_count
2                0.018737
4                0.230246
6                1.827501

In [5]:
x = np.array([1,-2])/np.array([1,2]).max()
x

array([ 0.5, -1. ])