In [1]:
from time import perf_counter
start = perf_counter()
from shapely.geometry import Point
print(f'imported Point in {perf_counter() - start:.3f} sec')
start = perf_counter()
import geopandas as gpd
print(f'imported gpd in {perf_counter() - start:.3f} sec')
start = perf_counter()
import pandas as pd
print(f'imported pd in {perf_counter() - start:.3f} sec')
start = perf_counter()
import numpy as np
print(f'imported np in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.data_gen.region_generator import RegionGenerator
print(f'imported RegionGen in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.data.measurment import Measurement
print(f'imported Measurement in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.grouping.brute_force import Brute_Force
print(f'imported BruteF in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.controller.benchmark_runner import BenchmarkRunner
print(f'imported Benchmark in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.grouping.k_means import K_Means
print(f'imported K-Means in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.animation.animation import Animation
print(f'imported Animation in {perf_counter() - start:.3f} sec')
start = perf_counter()
import plotly.graph_objects as go
print(f'imported Go in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.animation.trajectory import Trajectory
print(f'imported traj in {perf_counter() - start:.3f} sec')
start = perf_counter()
import plotly.express as px
print(f'imported px in {perf_counter() - start:.3f} sec')
start = perf_counter()
from src.utilities.seed_container import Seed_Container
print(f'imported SeedContainer in {perf_counter() - start:.3f} sec')

imported Point in 0.110 sec
imported gpd in 0.365 sec
imported pd in 0.000 sec
imported np in 0.000 sec
imported RegionGen in 0.149 sec
imported Measurement in 0.003 sec
imported BruteF in 0.329 sec
imported Benchmark in 0.002 sec
imported K-Means in 1.087 sec
imported Animation in 0.001 sec
imported Go in 0.000 sec
imported traj in 0.000 sec
imported px in 0.120 sec
imported SeedContainer in 0.000 sec

In [ ]:
seed_container = Seed_Container(seed=None)
region = RegionGenerator(seed_container=seed_container).random(6, 1, 10)
print()
algo = Brute_Force(distance_weight=0)
result = algo.group(region=region, animate=False)
# animation = Animation().play(algo.get_trajectory())

In [37]:
print(f'before: {result.get_autarky_without_groups():.3f}, after: {result.region_autarky():.3f}')

result.houses

before: 0.903, after: 1.000

    coordinate load  gen                   id  label
0  POINT (0 4)  [2]  [8]  X0.000000|Y4.000000      0
1  POINT (5 5)  [0]  [6]  X5.000000|Y5.000000      1
2  POINT (3 2)  [8]  [7]  X3.000000|Y2.000000      2
3  POINT (7 2)  [8]  [7]  X7.000000|Y2.000000      0
4  POINT (2 7)  [5]  [8]  X2.000000|Y7.000000      2
5  POINT (8 6)  [8]  [7]  X8.000000|Y6.000000      2

In [35]:
print(f'seed: {seed_container.seed()}')

seed: 2759657588

In [32]:
result = BenchmarkRunner(algo=Brute_Force(.5)).run(
    max_houses=6, 
    max_time_steps=24, 
    house_interval=2, 
    time_step_interval=24,
    file_location="C:/Users/steve/OneDrive/Dokumente/Universität/BA/Messung"
)
result

finished house 2/6 in 0.008 seconds
finished house 4/6 in 0.061 seconds
finished house 6/6 in 0.946 seconds

time_step_count        24
house_count
2                0.008496
4                0.061441
6                0.945733

In [33]:
x = np.array([1,-2])/np.array([1,2]).max()
x

array([ 0.5, -1. ])